apiVersion: v1
kind: Secret
metadata:
  name: reality-checker-secrets
  namespace: reality-checker
type: Opaque
data:
  # Base64-encoded secret values
  openai-api-key: <base64-encoded-key>
  twilio-account-sid: <base64-encoded-sid>
  twilio-auth-token: <base64-encoded-token>
  jwt-secret-key: <base64-encoded-secret>
  admin-password: <base64-encoded-password>
