name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        node-version: ["18"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt flake8 mypy
    - name: Format check (black)
      run: |
        pip install black
        black --check app tests
    - name: Lint (flake8)
      run: flake8 app tests
    - name: Type check (mypy)
      run: mypy app
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install frontend dependencies
      run: |
        cd dashboard
        npm ci
    - name: Build frontend
      run: |
        cd dashboard
        npm run build
    - name: Run tests
      run: pytest --maxfail=1 --disable-warnings -q
