name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    name: Python Tests (fast)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fast test suite
        env:
          PYTHONPATH: .
        run: |
          pytest -m "not slow and not integration and not performance and not e2e" --maxfail=1 -q

  dashboard-tests:
    name: Dashboard Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'dashboard/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run dashboard tests
        env:
          CI: true
        run: npm test -- --watchAll=false
